frase= 'Curso Em Video Python'
print(len(frase))
print(frase[9])
print(frase[9:13])
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(frase.count('o'))
print(frase.count('o',0,13))
print(frase.find('deo'))
print(frase.find('Android'))
print('Curso' in frase)
print(frase.replace('Python','Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase02= '   Aprenda Python  '
print(frase02.strip())
print(frase02.rstrip())
print(frase02.lstrip())
print(frase.split())
print('-'.join(frase.split()))